name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install requests pyinstaller
      - name: Build
        run: |
          pyinstaller --onefile --name bb_sync_${{ matrix.os }} bb_sync.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bb_sync_${{ matrix.os }}
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist_all
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist_all/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
