name: Release

# Trigger on tags (v*) and also on merges/pushes to master so we can create
# an automatic release when code is merged to master.
on:
  push:
    branches: [ master ]
    tags:
      - "v*"

# Allow the workflow token to create releases and upload assets
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install requests pyinstaller
      - name: Build
        run: |
          pyinstaller --onefile --name bb_sync_${{ matrix.os }} bb_sync.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bb_sync_${{ matrix.os }}
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist_all
      - name: Determine release tag
        id: get_tag
        run: |
          python - <<'PY'
          import tomllib, os
          tag = ''
          try:
              with open('pyproject.toml', 'rb') as f:
                  data = tomllib.load(f)
                  if isinstance(data, dict):
                      tag = data.get('project', {}).get('version', '')
                      if tag:
                          tag = 'v' + tag
          except Exception:
              tag = ''
          if not tag:
              from datetime import datetime
              sha = os.environ.get('GITHUB_SHA', '')
              short = sha[:7] if sha else 'local'
              tag = f"v{datetime.utcnow().strftime('%Y%m%d')}-{short}"
          print(tag)
          # Export to GITHUB_OUTPUT for step outputs
          with open(os.environ['GITHUB_OUTPUT'], 'a') as out:
              out.write(f"tag={tag}\n")
          PY
      - name: Zip artifacts
        run: |
          cd dist_all
          zip -r ../release_assets.zip . || true

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: "Release ${{ steps.get_tag.outputs.tag }}"
          body: "Automated release created from master push ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release_assets.zip
          asset_name: release_assets.zip
          asset_content_type: application/zip
